hmrc/fh-registration-frontend

- app/uk/gov/hmrc/fhregistrationfrontend/connectors/DFSUrls.scala
- app/uk/gov/hmrc/fhregistrationfrontend/controllers/Application.scala
- conf/application.conf
- test/AppUnitGenerator.scala
- test/uk/gov/hmrc/fhregistrationfrontend/controllers/ApplicationControllerSpec.scala
tested locally, the businessType that business-customer-frontend return is "Sole Trader"
> FHDDS-613: redirect to right form

- app/uk/gov/hmrc/fhregistrationfrontend/controllers/Application.scala
- app/uk/gov/hmrc/fhregistrationfrontend/views/acknowledgement.scala.html
- conf/app.routes
- conf/messages
- public/stylesheets/fh.css
just the template - routes need wiring up
> Fhdds 772 acknowledgement page

- app/uk/gov/hmrc/fhregistrationfrontend/views/forms/business_customers.scala.html
- app/uk/gov/hmrc/fhregistrationfrontend/views/forms/business_partners.scala.html
- app/uk/gov/hmrc/fhregistrationfrontend/views/forms/business_status.scala.html
- app/uk/gov/hmrc/fhregistrationfrontend/views/forms/company_officers.scala.html
- app/uk/gov/hmrc/fhregistrationfrontend/views/forms/company_registration_number.scala.html
- app/uk/gov/hmrc/fhregistrationfrontend/views/forms/contact_person.scala.html
- app/uk/gov/hmrc/fhregistrationfrontend/views/forms/date_of_incorporation.scala.html
- app/uk/gov/hmrc/fhregistrationfrontend/views/forms/has_other_storage_premises.scala.html
- app/uk/gov/hmrc/fhregistrationfrontend/views/forms/importing_activities.scala.html
- app/uk/gov/hmrc/fhregistrationfrontend/views/forms/main_business_address.scala.html
- app/uk/gov/hmrc/fhregistrationfrontend/views/forms/national_insurance_number.scala.html
- app/uk/gov/hmrc/fhregistrationfrontend/views/forms/other_storage_premises.scala.html
- app/uk/gov/hmrc/fhregistrationfrontend/views/forms/storage_premise.scala.html
- app/uk/gov/hmrc/fhregistrationfrontend/views/forms/trading_name.scala.html
- app/uk/gov/hmrc/fhregistrationfrontend/views/forms/vat_registration.scala.html
- app/uk/gov/hmrc/fhregistrationfrontend/views/helpers/Back.scala.html
- app/uk/gov/hmrc/fhregistrationfrontend/views/helpers/SubmitButtons.scala.html
- app/uk/gov/hmrc/fhregistrationfrontend/views/saved.scala.html
- public/javascripts/fh.js
continue or delete links to be wired up.
> Fhdds 829 save 4 later ui

- app/uk/gov/hmrc/fhregistrationfrontend/views/helpers/SummaryAddress.scala.html
- app/uk/gov/hmrc/fhregistrationfrontend/views/helpers/SummaryRow.scala.html
simple classname added to summary value column for test use
> summaryClassForTest: added class for all summary form data vals

- app/uk/gov/hmrc/fhregistrationfrontend/views/helpers/SummaryRowParams.scala
- app/uk/gov/hmrc/fhregistrationfrontend/views/saved.scala.html
showed test result via unit test
> FHDDS-830: dates display like: 05 May 1988

- app/uk/gov/hmrc/fhregistrationfrontend/controllers/Application.scala
- app/uk/gov/hmrc/fhregistrationfrontend/views/confirm_delete_section.scala.html
- app/uk/gov/hmrc/fhregistrationfrontend/views/forms/business_partners.scala.html
- app/uk/gov/hmrc/fhregistrationfrontend/views/forms/company_officers.scala.html
- app/uk/gov/hmrc/fhregistrationfrontend/views/forms/storage_premise.scala.html
- app/uk/gov/hmrc/fhregistrationfrontend/views/helpers/business_partners_liability_partnership.scala.html
- app/uk/gov/hmrc/fhregistrationfrontend/views/helpers/business_partners_sole_proprietor.scala.html
- conf/app.routes
- conf/messages
still needs back end for delete and enforcement of minimum list length rules - but structure here now for putting these in
> Fhdds 832 repeating section remove action

- app/uk/gov/hmrc/fhregistrationfrontend/actions/EnrolledUserAction.scala
- app/uk/gov/hmrc/fhregistrationfrontend/actions/FrontendAction.scala
- app/uk/gov/hmrc/fhregistrationfrontend/actions/JourneyAction.scala
- app/uk/gov/hmrc/fhregistrationfrontend/actions/PageAction.scala
- app/uk/gov/hmrc/fhregistrationfrontend/actions/ResumeJourneyAction.scala
- app/uk/gov/hmrc/fhregistrationfrontend/actions/SummaryAction.scala
- app/uk/gov/hmrc/fhregistrationfrontend/actions/UserAction.scala
- app/uk/gov/hmrc/fhregistrationfrontend/controllers/AmendmentController.scala
- app/uk/gov/hmrc/fhregistrationfrontend/controllers/Application.scala
- app/uk/gov/hmrc/fhregistrationfrontend/controllers/DeclarationController.scala
- app/uk/gov/hmrc/fhregistrationfrontend/controllers/ExternalUrls.scala
- app/uk/gov/hmrc/fhregistrationfrontend/controllers/FormPageController.scala
- app/uk/gov/hmrc/fhregistrationfrontend/controllers/SummaryController.scala
Reverts hmrc/fh-registration-frontend#84
> Revert "Fhdds 875 error pages"

- app/uk/gov/hmrc/fhregistrationfrontend/forms/models/BusinessEntityApplication.scala
- app/uk/gov/hmrc/fhregistrationfrontend/models/des/AdditionalBusinessInformationwithType.scala
- app/uk/gov/hmrc/fhregistrationfrontend/services/mapping/DesToForm.scala
- app/uk/gov/hmrc/fhregistrationfrontend/services/mapping/FormToDes.scala
- resources/des/subscription-create.schema.json
- resources/des/subscription-display.schema.json
- test/resources/json/valid/display/limited-company/fhdds-limited-company-minimum.json
Display API updated to
v2.2 - 06 Feb 2018 - premises is optional object now.
Create/Update API updated to
v6.5 - 19 Mar 2018 - Changed the URI as it was clashing with existing subscription API's
> FHDDS-963 Premises are optional. Update to latest display api

- app/uk/gov/hmrc/fhregistrationfrontend/controllers/Application.scala
- it/uk/gov/hmrc/fhregistrationfrontend/controllers/ApplicationControllerIntegrationSpec.scala
- it/uk/gov/hmrc/fhregistrationfrontend/controllers/FormPageControllerIntegrationSpec.scala
- it/uk/gov/hmrc/fhregistrationfrontend/controllers/SummaryControllerIntegrationSpec.scala
- it/uk/gov/hmrc/fhregistrationfrontend/controllers/WithdrawalControllerIntegrationSpec.scala
- it/uk/gov/hmrc/fhregistrationfrontend/testsupport/TestConfiguration.scala
- it/uk/gov/hmrc/fhregistrationfrontend/testsupport/TestHelper.scala
- it/uk/gov/hmrc/fhregistrationfrontend/testsupport/preconditions/BusinessCustomerFrontendStub.scala
- it/uk/gov/hmrc/fhregistrationfrontend/testsupport/preconditions/KeyStoreStub.scala
- it/uk/gov/hmrc/fhregistrationfrontend/testsupport/preconditions/Save4LaterStub.scala
- it/uk/gov/hmrc/fhregistrationfrontend/testsupport/preconditions/UserStub.scala
added "integration" tests for apis
> Fhdds 964 integration test

- app/uk/gov/hmrc/fhregistrationfrontend/forms/mappings/Mappings.scala
Merge Hotfixes to master branch
> Fhdds 1013 hotfix minyear

- app/uk/gov/hmrc/fhregistrationfrontend/actions/UserAction.scala
- it/uk/gov/hmrc/fhregistrationfrontend/emailverification/DraftApplicationPreV2.scala
- it/uk/gov/hmrc/fhregistrationfrontend/testsupport/preconditions/UserStub.scala
- test/uk/gov/hmrc/fhregistrationfrontend/actions/EmailVerificationActionSpec.scala
- test/uk/gov/hmrc/fhregistrationfrontend/actions/EnrolledUserActionSpec.scala
- test/uk/gov/hmrc/fhregistrationfrontend/actions/JourneyActionSpec.scala
- test/uk/gov/hmrc/fhregistrationfrontend/actions/JourneyRequestBuilder.scala
- test/uk/gov/hmrc/fhregistrationfrontend/actions/NewApplicationActionSpec.scala
- test/uk/gov/hmrc/fhregistrationfrontend/actions/NoPendingSubmissionFilterSpec.scala
- test/uk/gov/hmrc/fhregistrationfrontend/actions/NotAdminUserFilterSpec.scala
- test/uk/gov/hmrc/fhregistrationfrontend/actions/StartAmendmentActionSpec.scala
- test/uk/gov/hmrc/fhregistrationfrontend/actions/StartVariationActionSpec.scala
- test/uk/gov/hmrc/fhregistrationfrontend/actions/UserActionSpec.scala
- test/uk/gov/hmrc/fhregistrationfrontend/teststubs/ActionsMock.scala
- test/uk/gov/hmrc/fhregistrationfrontend/teststubs/UserTestData.scala
Prevent agents from entering the service.
> DLS-196: Block Agents

- project/FrontendBuild.scala
- project/plugins.sbt
> DLS-246: Bootstrap library upgrades

- project/FrontendBuild.scala
DLS-1323 play-ui version updated to 8.3.0 (minor)
> DLS-1323 FHDDS tax platform update

- build.sbt
- project/plugins.sbt
DLS-2418 Library versions upgraded
> DLS-2418 Library versions upgraded

- app/uk/gov/hmrc/fhregistrationfrontend/views/helpers/SummaryAddressBlock.scala.html
implemented solution to ignore <br> by screen reader
> DLS-2919 FHDDS - Each address line repeats twice on Summary Page

- app/uk/gov/hmrc/fhregistrationfrontend/config/FrontendAppConfig.scala
- app/uk/gov/hmrc/fhregistrationfrontend/views/govuk_wrapper.scala.html
- build.sbt
- conf/application.conf
FHDDS: Remove GA snippets and point to production
> DLS-3973  GTM - FHDDS: Remove GA snippets and point to production

- app/uk/gov/hmrc/fhregistrationfrontend/views/govuk_wrapper.scala.html
- public/javascripts/fh.js
> DLS-3973 GTM - FHDDS: Remove GA snippets and point to production

- app/uk/gov/hmrc/fhregistrationfrontend/views/forms/vat_registration.scala.html
- app/uk/gov/hmrc/fhregistrationfrontend/views/helpers/SaveForLater.scala.html
- conf/application.conf
ticket details -> https://jira.tools.tax.service.gov.uk/browse/DLS-5971
> DLS-5971 bug ticket

- app/uk/gov/hmrc/fhregistrationfrontend/views/ViewHelpers.scala
- app/uk/gov/hmrc/fhregistrationfrontend/views/forms/company_registration_number.scala.html
ticket details -> https://jira.tools.tax.service.gov.uk/browse/DLS-5900
Screen shots:
> DLS-5900 crn page

- app/uk/gov/hmrc/fhregistrationfrontend/views/emailverification/email_options.scala.html
- conf/messages
ticket details -> https://jira.tools.tax.service.gov.uk/browse/DLS-5897
> DLS-5897 email contact page

- app/uk/gov/hmrc/fhregistrationfrontend/forms/definitions/DateOfIncorporationForm.scala
- app/uk/gov/hmrc/fhregistrationfrontend/forms/mappings/Mappings.scala
- app/uk/gov/hmrc/fhregistrationfrontend/views/forms/date_of_incorporation.scala.html
- conf/messages
- test/uk/gov/hmrc/fhregistrationfrontend/forms/definitions/DateOfIncorporationSpecs.scala
ticket details -> https://jira.tools.tax.service.gov.uk/browse/DLS-5901
https://user-images.githubusercontent.com/88194246/189632639-e0514d79-9466-4ed5-88f7-2e02e7fa9f3d.png)
rcontent.com/88194246/189632761-18dd5518-dffd-4714-bdde-2002
eeb114
20.png)
> Dls 5901 date

- app/uk/gov/hmrc/fhregistrationfrontend/views/forms/national_insurance_number.scala.html
- app/uk/gov/hmrc/fhregistrationfrontend/views/helpers/SaveForLater.scala.html
update NINO page to new components 
incorporated Priyanka's vat error fix save for later page
> DLS-5913 NINO

- app/uk/gov/hmrc/fhregistrationfrontend/views/forms/trading_name.scala.html
ticket details -> https://jira.tools.tax.service.gov.uk/browse/DLS-5902
Screen shots
> DLS-5902 trading name form

- app/uk/gov/hmrc/fhregistrationfrontend/views/helpers/SurveyLinkNew.scala.html
- app/uk/gov/hmrc/fhregistrationfrontend/views/registrationstatus/status.scala.html
- app/uk/gov/hmrc/fhregistrationfrontend/views/registrationstatus/statusHeading.scala.html
- app/uk/gov/hmrc/fhregistrationfrontend/views/registrationstatus/statusMoreInfo.scala.html
- app/uk/gov/hmrc/fhregistrationfrontend/views/registrationstatus/statusNewApplication.scala.html
- app/uk/gov/hmrc/fhregistrationfrontend/views/registrationstatus/statusSteps.scala.html
- app/uk/gov/hmrc/fhregistrationfrontend/views/registrationstatus/statusWhatHappensNext.scala.html
ticket details ->
https://jira.tools.tax.service.gov.uk/browse/DLS-5915
> DLS-5915 status page

- app/uk/gov/hmrc/fhregistrationfrontend/views/emailverification/email_verified.scala.html
ticket details -> https://jira.tools.tax.service.gov.uk/browse/DLS-5955
> Dls 5955 emailverified

- app/uk/gov/hmrc/fhregistrationfrontend/views/forms/business_status.scala.html
ticket details -> https://jira.tools.tax.service.gov.uk/browse/DLS-6005
> DLS-6005 bug fix

- app/uk/gov/hmrc/fhregistrationfrontend/views/emailverification/email_pending_verification.scala.html
ticket details -> https://jira.tools.tax.service.gov.uk/browse/DLS-5954
> Dls 5954 email verify

- app/uk/gov/hmrc/fhregistrationfrontend/views/emailverification/email_change_start.scala.html
ticket details -> https://jira.tools.tax.service.gov.uk/browse/DLS-5957
> DLS-5957 email change

- app/uk/gov/hmrc/fhregistrationfrontend/views/ViewHelpers.scala
- app/uk/gov/hmrc/fhregistrationfrontend/views/emailverification/email_edit.scala.html
- conf/messages
Updated to new components.  Inset text at bottom - line is thicker due to the component - Errors go to contact us page as it was prior to the update.
> Dls 5956 edit email

- app/uk/gov/hmrc/fhregistrationfrontend/views/continue_delete.scala.html
ticket details -> https://jira.tools.tax.service.gov.uk/browse/DLS-5914
> DLS-5914 delete or continue

- app/uk/gov/hmrc/fhregistrationfrontend/views/forms/business_customers.scala.html
> DLS-5907: Frontend upgrade for business customer page

- app/uk/gov/hmrc/fhregistrationfrontend/views/saved.scala.html
ticket details -> https://jira.tools.tax.service.gov.uk/browse/DLS-5960
> DLS-5960 progress saved

- app/uk/gov/hmrc/fhregistrationfrontend/controllers/DeregistrationController.scala
- app/uk/gov/hmrc/fhregistrationfrontend/views/deregistration/deregistration_acknowledgement.scala.html
Page updated to use new play components.  Update to Time format to be consistent with reg journey acknowledgement page
> DLS-5965-update to deregistration acknowledgement page

- app/uk/gov/hmrc/fhregistrationfrontend/controllers/DeregistrationController.scala
- app/uk/gov/hmrc/fhregistrationfrontend/forms/deregistration/DeregistrationReasonForm.scala
- app/uk/gov/hmrc/fhregistrationfrontend/views/deregistration/deregistration_reason.scala.html
- conf/messages
ticket details -> https://jira.tools.tax.service.gov.uk/browse/DLS-5962
> Dls 5962 dereg

- app/uk/gov/hmrc/fhregistrationfrontend/controllers/WithdrawalController.scala
- app/uk/gov/hmrc/fhregistrationfrontend/views/deregistration/deregistration_acknowledgement.scala.html
- app/uk/gov/hmrc/fhregistrationfrontend/views/withdrawals/withdrawal_acknowledgement.scala.html
Ticket https://jira.tools.tax.service.gov.uk/browse/DLS-5918
Updated withdrawal controller to use java time to be consistent with other acknowledgement pages
> Dls 5918 fhdds withdrawal ack page

- app/uk/gov/hmrc/fhregistrationfrontend/controllers/DeregistrationController.scala
- app/uk/gov/hmrc/fhregistrationfrontend/views/deregistration/deregistration_confirm.scala.html
- app/uk/gov/hmrc/fhregistrationfrontend/views/forms/contact_person.scala.html
- conf/messages
I have tried to align the radios but it doesn't render correctly. This is what this looks like. 
Functions well with buttons stacked as seen below:
> Dls 5964 de registration confirmation

- app/uk/gov/hmrc/fhregistrationfrontend/controllers/WithdrawalController.scala
- app/uk/gov/hmrc/fhregistrationfrontend/views/forms/business_status.scala.html
- app/uk/gov/hmrc/fhregistrationfrontend/views/forms/importing_activities.scala.html
- app/uk/gov/hmrc/fhregistrationfrontend/views/forms/national_insurance_number.scala.html
- app/uk/gov/hmrc/fhregistrationfrontend/views/forms/trading_name.scala.html
- app/uk/gov/hmrc/fhregistrationfrontend/views/forms/vat_registration.scala.html
- app/uk/gov/hmrc/fhregistrationfrontend/views/withdrawals/withdrawal_confirm.scala.html
- conf/messages
ticket details -> https://jira.tools.tax.service.gov.uk/browse/DLS-5919
4](https://user-images.githubusercontent.com/88194246/205107180-9c7c9799-75ad-454b-8353-40e593299caa.png)
> Dls 5919 withdraw confirm

- app/uk/gov/hmrc/fhregistrationfrontend/forms/definitions/MainBusinessAddressForm.scala
- app/uk/gov/hmrc/fhregistrationfrontend/views/forms/main_business_address.scala.html
- conf/messages
> DLS-5899: Frontend upgrade

- app/uk/gov/hmrc/fhregistrationfrontend/controllers/BusinessPartnersIndividualsAndSoleProprietorsNinoController.scala
- app/uk/gov/hmrc/fhregistrationfrontend/controllers/BusinessPartnersIndividualsAndSoleProprietorsPartnerNameController.scala
- app/uk/gov/hmrc/fhregistrationfrontend/controllers/BusinessPartnersTradingNameController.scala
- app/uk/gov/hmrc/fhregistrationfrontend/controllers/BusinessPartnersVatRegistrationNumberController.scala
- app/uk/gov/hmrc/fhregistrationfrontend/pages/businessPartners/IndividualsAndSoleProprietorsNinoPage.scala
- conf/app.routes
- it/uk/gov/hmrc/fhregistrationfrontend/controllers/BusinessPartnersIndividualsAndSoleProprietorsNinoControllerISpec.scala
- it/uk/gov/hmrc/fhregistrationfrontend/controllers/BusinessPartnersIndividualsAndSoleProprietorsPartnerNameControllerISpec.scala
- it/uk/gov/hmrc/fhregistrationfrontend/controllers/BusinessPartnersNewFlowDisabledISpec.scala
- it/uk/gov/hmrc/fhregistrationfrontend/controllers/BusinessPartnersTradingNameControllerISpec.scala
- test/uk/gov/hmrc/fhregistrationfrontend/controllers/BusinessPartnersIndividualsAndSoleProprietorsNinoControllerSpec.scala
- test/uk/gov/hmrc/fhregistrationfrontend/controllers/BusinessPartnersIndividualsAndSoleProprietorsPartnerNameControllerSpec.scala
Add Normal/CheckMode 
update urls 
add IndividualsAndSoleProprietorsPage 
Update tests
> Add new page, update tests

- app/uk/gov/hmrc/fhregistrationfrontend/views/summary/CompanyOfficerIndividual.scala.html
- app/uk/gov/hmrc/fhregistrationfrontend/views/summary/helpers/CompanyOrIndividualHelper.scala
> DLS-10162 - wrong message key

- app/uk/gov/hmrc/fhregistrationfrontend/views/business_type.scala.html
Added error prefix to page title
> DLS-9170 - added error prefix to page title

- app/uk/gov/hmrc/fhregistrationfrontend/views/businessPartners/v2/business_partners_has_utr_number.scala.html
- conf/messages
> DLS-10177 - updated exposed label

- app/uk/gov/hmrc/fhregistrationfrontend/views/forms/company_officers.scala.html
- app/uk/gov/hmrc/fhregistrationfrontend/views/ltd_summary.scala.html
- app/uk/gov/hmrc/fhregistrationfrontend/views/summary/helpers/CompanyOfficersHelper.scala
https://jira.tools.tax.service.gov.uk/browse/DLS-10156
> DLS-10156 Move delete company officer link

- app/uk/gov/hmrc/fhregistrationfrontend/actions/PageAction.scala
- app/uk/gov/hmrc/fhregistrationfrontend/config/FrontendAppConfig.scala
- app/uk/gov/hmrc/fhregistrationfrontend/services/SummaryConfirmationService.scala
- app/uk/gov/hmrc/fhregistrationfrontend/services/helper/Retryable/Retryable.scala
- conf/application.conf
- test/uk/gov/hmrc/fhregistrationfrontend/actions/PageActionSpec.scala
- test/uk/gov/hmrc/fhregistrationfrontend/services/SummaryConfirmationServiceSpecs.scala
- test/uk/gov/hmrc/fhregistrationfrontend/teststubs/FormTestData.scala
Create Summary Confirmation Service with functions (Keystore)
> Create SummaryConfirmationService with functions

- app/uk/gov/hmrc/fhregistrationfrontend/config/FrontendAppConfig.scala
- app/uk/gov/hmrc/fhregistrationfrontend/services/SummaryConfirmationLocalService.scala
- app/uk/gov/hmrc/fhregistrationfrontend/services/SummaryConfirmationService.scala
- conf/application.conf
- test/uk/gov/hmrc/fhregistrationfrontend/models/SummaryConfirmationSpec.scala
- test/uk/gov/hmrc/fhregistrationfrontend/services/SummaryConfirmationServiceSpecs.scala
[FHDDS] - Introduce feature flag to switch between new and old cache in SummaryConfirmationService - Keystore
> DLS-10582: Introduce feature flag to switch between new and old cache in SummaryConfirmationService - Keystore

- app/uk/gov/hmrc/fhregistrationfrontend/views/forms/contact_person.scala.html
> DLS-11295: Corrects pageScripts tag in contact_person.html
